### ISSUE TITLE
hUGETracker sample appears to be wrong

### ISSUE THREAD

**Issue by ISSOtm** [datguywitha3ds/CBT-FX#2]
The hUGEDriver API [requires *two* parameters](https://github.com/SuperDisk/hUGEDriver/blob/cc0867436a2081be481fad87163dda409b5521f9/include/hUGEDriver.h#L103-L104) for `hUGE_mute_channel`, and the two lines are identical, probably a c/c mistake.

**Comment by datguywitha3ds** [comment]
Fixed, now there's different macros for turning a channel on and off
