### ISSUE TITLE
init documentation is out of date

### ISSUE THREAD

**Issue by mhughson** [datguywitha3ds/CBT-FX#3]
In the readme.md it says:

> When you need to play a sound effect, call CBTFX_init(&your_SFX_name[0][0], your_SFX_name_Length)

Now ever, the function takes 4 parameters, and should instead be somethign like:

`CBTFX_init(&SFX_00[0][0], SFX_00_Length, SFX_00_Priority, SFX_00_CH_Used);`

**Comment by datguywitha3ds** [comment]
Fixed with the revamp, now the init function takes one parameter, sorry for that ^^'
