### ISSUE TITLE
the tutorial made sense up until actually exporting the sounds

### ISSUE THREAD

**Issue by Skittles666** [datguywitha3ds/CBT-FX#5]
so it says to "Use the hammer2cbt.py script to convert your desired effects, it takes a few necessary arguments: etc..."
where should i be putting these "arguments"
i drag and drop all 3 files to the py script and nothing happens, and i have no idea where you expect me to input those things

**Comment by coffeevalenbat** [comment]
hammer2cbt.py (And most python tools of it's style) Are supposed to be used through the command line interface. I'm not sure how exactly the python enviroment is on windows (I'm guessing you're doing this on windows) but it shouldn't be too different, just open a command line, call the script and you'll see the help message.
